# Generated by Django 5.0 on 2026-04-30 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_created_at_alter_package_updated_at'),
        ('reviews', '0003_title_comment_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='packages.package', verbose_name='Paquete'),
        ),
    ]
