# Generated by Django 5.0 on 2026-05-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto (USD)'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida aproximada'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='destination_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Destino deseado'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('inquiry', 'Consulta general'), ('quote', 'Solicitud de cotización')], default='inquiry', max_length=16, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='Intereses / actividades deseadas'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='num_adults',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Adultos'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='num_children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Niños'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de regreso aproximada'),
        ),
    ]
