# Generated by Django 5.0 on 2025-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Número de vuelo')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen')),
                ('destination', models.CharField(max_length=100, verbose_name='Destino')),
                ('departure_time', models.DateTimeField(verbose_name='Hora de salida')),
                ('arrival_time', models.DateTimeField(verbose_name='Hora de llegada')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['departure_time'],
            },
        ),
    ]
