# Generated by Django 5.0 on 2025-10-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=64)),
                ('departure', models.CharField(blank=True, max_length=128, null=True)),
                ('arrival', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
