# Generated by Django 5.0 on 2025-10-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='avalable_seats',
            new_name='available_seats',
        ),
    ]
