# Generated by Django 5.0 on 2025-10-27 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline_code',
            field=models.CharField(max_length=10, verbose_name='Código de aerolínea'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline_name',
            field=models.CharField(max_length=100, verbose_name='Aerolínea'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Hora de llegada'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(verbose_name='Asientos disponibles'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='baggage_allowance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipaje permitido'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_airport',
            field=models.CharField(max_length=100, verbose_name='Aeropuerto de destino'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_city',
            field=models.CharField(max_length=100, verbose_name='Ciudad de destino'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_class',
            field=models.CharField(max_length=50, verbose_name='Clase de vuelo'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=20, verbose_name='Número de vuelo'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_airport',
            field=models.CharField(max_length=100, verbose_name='Aeropuerto de origen'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_city',
            field=models.CharField(max_length=100, verbose_name='Ciudad de origen'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
