# Generated by Django 5.0 on 2026-06-06 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Teléfono')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto WhatsApp',
                'verbose_name_plural': 'Contactos WhatsApp',
                'db_table': 'whatsapp_contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('message_template', models.TextField(verbose_name='Mensaje')),
                ('delay_between_ms', models.PositiveIntegerField(default=5000, verbose_name='Delay entre mensajes (ms)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('running', 'En ejecución'), ('paused', 'Pausada'), ('completed', 'Completada'), ('failed', 'Fallida')], default='draft', max_length=15)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_campaigns', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.ManyToManyField(blank=True, related_name='campaigns', to='whatsapp.whatsappcontact')),
            ],
            options={
                'verbose_name': 'Campaña WhatsApp',
                'verbose_name_plural': 'Campañas WhatsApp',
                'db_table': 'whatsapp_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='whatsapp.whatsappcontact')),
            ],
            options={
                'verbose_name': 'Conversación WhatsApp',
                'verbose_name_plural': 'Conversaciones WhatsApp',
                'db_table': 'whatsapp_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Entrante'), ('outgoing', 'Saliente')], max_length=10)),
                ('content', models.TextField(verbose_name='Contenido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('queued', 'En cola'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=15)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado a las')),
                ('waha_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappconversation')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'db_table': 'whatsapp_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
