# Generated by Django 5.0 on 2025-10-27 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias_paquetes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paquete', 'verbose_name_plural': 'Paquetes'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='available_from',
            field=models.DateField(default='2024-01-01', verbose_name='Disponible desde'),
        ),
        migrations.AddField(
            model_name='package',
            name='available_until',
            field=models.DateField(default='2024-12-31', verbose_name='Disponible hasta'),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_nights',
            field=models.PositiveIntegerField(default=0, verbose_name='Duración en noches'),
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='package',
            name='includes',
            field=models.JSONField(default=list, verbose_name='Incluye'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='package',
            name='max_people',
            field=models.PositiveIntegerField(default=10, verbose_name='Máximo de personas'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_adult',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio adulto'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_child',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio niño'),
        ),
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Duración en días'),
        ),
        migrations.AlterModelTable(
            name='package',
            table='paquetes_turisticos',
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.category', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Día número')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('activities', models.JSONField(default=list, verbose_name='Actividades')),
                ('meals_included', models.JSONField(default=list, verbose_name='Comidas incluidas')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='packages.package', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'db_table': 'itinerarios_paquete',
                'ordering': ['day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
    ]
