# Generated by Django 5.0 on 2026-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_created_at_alter_package_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)'),
        ),
    ]
