# Generated by Django 5.0 on 2025-10-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_options_and_more'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(blank=True, null=True, verbose_name='Amenidades'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de check-in'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de check-out'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='destinations.destination', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está activo'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por noche'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.PositiveIntegerField(default=3, verbose_name='Calificación de estrellas'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='total_rooms',
            field=models.PositiveIntegerField(verbose_name='Total de habitaciones'),
        ),
    ]
