# Generated by Django 5.0 on 2025-10-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='start_rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
