# Generated by Django 5.0 on 2025-10-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='flightbooking',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='flightbooking',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
