# Generated by Django 5.0 on 2025-10-27 15:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_package_id_booking_package_and_more'),
        ('flights', '0002_flight_created_at'),
        ('hotels', '0001_initial'),
        ('packages', '0002_remove_package_includes_package_includes_flight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-booking_date',), 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='flightbooking',
            options={'verbose_name': 'Reserva de vuelo', 'verbose_name_plural': 'Reservas de vuelo'},
        ),
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={'verbose_name': 'Reserva de hotel', 'verbose_name_plural': 'Reservas de hotel'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Pasajero', 'verbose_name_plural': 'Pasajeros'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='Número de reserva'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de adultos'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de niños'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_infants',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de infantes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.package', verbose_name='Paquete'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto pagado'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'No pagado'), ('partial', 'Pago parcial'), ('paid', 'Pagado'), ('refunded', 'Reembolsado')], default='unpaid', max_length=16, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de regreso'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True, verbose_name='Solicitudes especiales'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', max_length=16, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impuestos'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto total'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de viaje'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to='bookings.booking', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_type',
            field=models.CharField(choices=[('outbound', 'Ida'), ('return', 'Regreso')], default='outbound', max_length=8, verbose_name='Tipo de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_reservations', to='flights.flight', verbose_name='Vuelo'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='num_passengers',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de pasajeros'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='pnr_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Número PNR'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio por persona'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='seat_numbers',
            field=models.TextField(blank=True, null=True, verbose_name='Números de asiento'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='bookings.booking', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_in_date',
            field=models.DateField(verbose_name='Fecha de entrada'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_out_date',
            field=models.DateField(verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Número de confirmación'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_reservations', to='hotels.hotel', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='num_rooms',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de habitaciones'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio por noche'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tipo de habitación'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='total_nights',
            field=models.PositiveIntegerField(default=1, verbose_name='Total de noches'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passenger_type',
            field=models.CharField(choices=[('adult', 'Adulto'), ('child', 'Niño'), ('infant', 'Infante')], default='adult', max_length=8, verbose_name='Tipo de pasajero'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Número de pasaporte'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='title',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Título'),
        ),
    ]
