# Generated by Django 5.0 on 2025-10-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del destino')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/', verbose_name='Imagen principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destinos',
                'ordering': ['name'],
            },
        ),
    ]
