# Generated by Django 5.0 on 2025-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at'], 'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_season',
            field=models.CharField(max_length=100, verbose_name='Mejor temporada'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(max_length=50, verbose_name='Continente'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Es popular'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='Descripción corta'),
        ),
    ]
